name: Deploy to GitHub Pages

env:
    PROJECT_PATH: wrpc.ui.web/wrpc.ui.web.csproj
    OUTPUT_PATH: wrpc.ui.web/bin/Release/net8.0/browser-wasm/AppBundle
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0

    - name: Install wasm-tools
      run: dotnet workload install wasm-tools wasm-experimental

    - name: Install DotNetCompress
      run: dotnet tool install --global DotNetCompress --version 3.0.0 --no-cache

    - name: Publish .NET Project
      run: dotnet publish $PROJECT_PATH -c Release -o release --nologo

    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/wrpc\/" \/>/g' $OUTPUT_PATH/index.html

    - name: copy index.html to 404.html
      run: cp $OUTPUT_PATH/index.html $OUTPUT_PATH/404.html

    - name: Compress Output using Brotli
      run: DotNetCompress -d $OUTPUT_PATH/ -p "*.dll" "*.js" "*.wasm" --format br --threads 4

    - name: Compress Output using GZip
      run: DotNetCompress -d $OUTPUT_PATH -p "*.dll" "*.js" "*.wasm" --format gz --threads 4

    - name: Add .nojekyll file
      run: touch $OUTPUT_PATH/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ${{ env.OUTPUT_PATH }}
